from enum import StrEnum

from chelyzer_lichess.models import FullyAnnotatedGame


class Opening(StrEnum):
    """Enum for chess openings."""

    ALEKHINE_DEFENSE = "Alekhine Defense"
    AMAR_OPENING = "Amar Opening"
    AMAZON_ATTACK = "Amazon Attack"
    AMSTERDAM_ATTACK = "Amsterdam Attack"
    ANDERSSENS_OPENING = "Anderssen's Opening"
    AUSTRALIAN_DEFENSE = "Australian Defense"
    BARNES_DEFENSE = "Barnes Defense"
    BARNES_OPENING = "Barnes Opening"
    BENKO_GAMBIT = "Benko Gambit"
    BENKO_GAMBIT_ACCEPTED = "Benko Gambit Accepted"
    BENONI_DEFENSE = "Benoni Defense"
    BIRD_OPENING = "Bird Opening"
    BISHOPS_OPENING = "Bishop's Opening"
    BLACKMAR_DIEMER_GAMBIT = "Blackmar-Diemer Gambit"
    BLACKMAR_DIEMER_GAMBIT_ACCEPTED = "Blackmar-Diemer Gambit Accepted"
    BLUMENFELD_COUNTERGAMBIT = "Blumenfeld Countergambit"
    BLUMENFELD_COUNTERGAMBIT_ACCEPTED = "Blumenfeld Countergambit Accepted"
    BOGO_INDIAN_DEFENSE = "Bogo-Indian Defense"
    BONGCLOUD_ATTACK = "Bongcloud Attack"
    BORG_DEFENSE = "Borg Defense"
    CANARD_OPENING = "Canard Opening"
    CARO_KANN_DEFENSE = "Caro-Kann Defense"
    CARR_DEFENSE = "Carr Defense"
    CATALAN_OPENING = "Catalan Opening"
    CENTER_GAME = "Center Game"
    CENTER_GAME_ACCEPTED = "Center Game Accepted"
    CLEMENZ_OPENING = "Clemenz Opening"
    CZECH_DEFENSE = "Czech Defense"
    DANISH_GAMBIT = "Danish Gambit"
    DANISH_GAMBIT_ACCEPTED = "Danish Gambit Accepted"
    DURAS_GAMBIT = "Duras Gambit"
    DUTCH_DEFENSE = "Dutch Defense"
    DORY_DEFENSE = "Döry Defense"
    EAST_INDIAN_DEFENSE = "East Indian Defense"
    ELEPHANT_GAMBIT = "Elephant Gambit"
    ENGLISH_DEFENSE = "English Defense"
    ENGLISH_OPENING = "English Opening"
    ENGLISH_ORANGUTAN = "English Orangutan"
    ENGLUND_GAMBIT = "Englund Gambit"
    ENGLUND_GAMBIT_DECLINED = "Englund Gambit Declined"
    FOUR_KNIGHTS_GAME = "Four Knights Game"
    FRENCH_DEFENSE = "French Defense"
    FRIED_FOX_DEFENSE = "Fried Fox Defense"
    GLOBAL_OPENING = "Global Opening"
    GOLDSMITH_DEFENSE = "Goldsmith Defense"
    GROB_OPENING = "Grob Opening"
    GRUNFELD_DEFENSE = "Grünfeld Defense"
    GUNDERAM_DEFENSE = "Gunderam Defense"
    HIPPOPOTAMUS_DEFENSE = "Hippopotamus Defense"
    HORWITZ_DEFENSE = "Horwitz Defense"
    HUNGARIAN_OPENING = "Hungarian Opening"
    INDIAN_DEFENSE = "Indian Defense"
    IRISH_GAMBIT = "Irish Gambit"
    ITALIAN_GAME = "Italian Game"
    KANGAROO_DEFENSE = "Kangaroo Defense"
    KINGS_GAMBIT = "King's Gambit"
    KINGS_GAMBIT_ACCEPTED = "King's Gambit Accepted"
    KINGS_INDIAN_ATTACK = "King's Indian Attack"
    KINGS_INDIAN_ATTACK_WITH_BF5 = "King's Indian Attack, with Bf5"
    KINGS_INDIAN_ATTACK_WITH_E6 = "King's Indian Attack, with e6"
    KINGS_INDIAN_DEFENSE = "King's Indian Defense"
    KINGS_KNIGHT_OPENING = "King's Knight Opening"
    KINGS_PAWN_GAME = "King's Pawn Game"
    KINGS_PAWN_OPENING = "King's Pawn Opening"
    KADAS_OPENING = "Kádas Opening"
    LASKER_SIMUL_SPECIAL = "Lasker Simul Special"
    LATVIAN_GAMBIT = "Latvian Gambit"
    LATVIAN_GAMBIT_ACCEPTED = "Latvian Gambit Accepted"
    LEMMING_DEFENSE = "Lemming Defense"
    LONDON_SYSTEM = "London System"
    LONDON_SYSTEM_WITH_BD3 = "London System, with Bd3"
    LONDON_SYSTEM_WITH_BE2 = "London System, with Be2"
    MARIENBAD_SYSTEM = "Marienbad System"
    MEXICAN_DEFENSE = "Mexican Defense"
    MIESES_OPENING = "Mieses Opening"
    MIKENAS_DEFENSE = "Mikenas Defense"
    MODERN_DEFENSE = "Modern Defense"
    MONTEVIDEO_DEFENSE = "Montevideo Defense"
    NIMZO_INDIAN_DEFENSE = "Nimzo-Indian Defense"
    NIMZO_LARSEN_ATTACK = "Nimzo-Larsen Attack"
    NIMZOWITSCH_DEFENSE = "Nimzowitsch Defense"
    OLD_INDIAN_DEFENSE = "Old Indian Defense"
    OWEN_DEFENSE = "Owen Defense"
    PALEFACE_ATTACK = "Paleface Attack"
    PETROVS_DEFENSE = "Petrov's Defense"
    PHILIDOR_DEFENSE = "Philidor Defense"
    PIRC_DEFENSE = "Pirc Defense"
    POLISH_DEFENSE = "Polish Defense"
    POLISH_OPENING = "Polish Opening"
    POLISH_OPENING_WITH_D5 = "Polish Opening, with d5"
    PONZIANI_OPENING = "Ponziani Opening"
    PORTUGUESE_OPENING = "Portuguese Opening"
    PSEUDO_QUEENS_INDIAN_DEFENSE = "Pseudo Queen's Indian Defense"
    PTERODACTYL_DEFENSE = "Pterodactyl Defense"
    QUEENS_GAMBIT = "Queen's Gambit"
    QUEENS_GAMBIT_ACCEPTED = "Queen's Gambit Accepted"
    QUEENS_GAMBIT_DECLINED = "Queen's Gambit Declined"
    QUEENS_INDIAN_ACCELERATED = "Queen's Indian Accelerated"
    QUEENS_INDIAN_DEFENSE = "Queen's Indian Defense"
    QUEENS_PAWN_GAME = "Queen's Pawn Game"
    QUEENS_PAWN_MENGARINI_ATTACK = "Queen's Pawn, Mengarini Attack"
    RAPPORT_JOBAVA_SYSTEM = "Rapport-Jobava System"
    RAPPORT_JOBAVA_SYSTEM_WITH_E6 = "Rapport-Jobava System, with e6"
    RICHTER_VERESOV_ATTACK = "Richter-Veresov Attack"
    ROBATSCH_DEFENSE = "Robatsch Defense"
    RUBINSTEIN_OPENING = "Rubinstein Opening"
    RUY_LOPEZ = "Ruy Lopez"
    RETI_OPENING = "Réti Opening"
    SARAGOSSA_OPENING = "Saragossa Opening"
    SCANDINAVIAN_DEFENSE = "Scandinavian Defense"
    SCOTCH_GAME = "Scotch Game"
    SEMI_SLAV_DEFENSE = "Semi-Slav Defense"
    SEMI_SLAV_DEFENSE_ACCEPTED = "Semi-Slav Defense Accepted"
    SICILIAN_DEFENSE = "Sicilian Defense"
    SLAV_DEFENSE = "Slav Defense"
    SLAV_INDIAN = "Slav Indian"
    SODIUM_ATTACK = "Sodium Attack"
    ST_GEORGE_DEFENSE = "St. George Defense"
    TARRASCH_DEFENSE = "Tarrasch Defense"
    THREE_KNIGHTS_OPENING = "Three Knights Opening"
    TROMPOWSKY_ATTACK = "Trompowsky Attack"
    VALENCIA_OPENING = "Valencia Opening"
    VAN_GEET_OPENING = "Van Geet Opening"
    VANT_KRUIJS_OPENING = "Van't Kruijs Opening"
    VIENNA_GAMBIT_WITH_MAX_LANGE_DEFENSE = "Vienna Gambit, with Max Lange Defense"
    VIENNA_GAME = "Vienna Game"
    VULTURE_DEFENSE = "Vulture Defense"
    WADE_DEFENSE = "Wade Defense"
    WARE_DEFENSE = "Ware Defense"
    WARE_OPENING = "Ware Opening"
    YUSUPOV_RUBINSTEIN_SYSTEM = "Yusupov-Rubinstein System"
    ZAIRE_DEFENSE = "Zaire Defense"
    ZUKERTORT_OPENING = "Zukertort Opening"
    UNKNOWN = "?"

    @classmethod
    def from_game(cls, game: FullyAnnotatedGame) -> Opening:  # noqa: F821
        """Return an opening instance from the given game."""
        try:
            return Opening(game.opening.split(":")[0])
        except ValueError:
            return Opening.UNKNOWN
